USE portfolio_db;

INSERT INTO projects
    (project_name, code_link, deployed_link, description, languages, button_filter)
VALUES
    ('Password Generator', 'https://github.com/auzzie13/passwordGenerator', 'https://auzzie13.github.io/passwordGenerator', 'Application that generates a random password based on user-selected criteria. This app runs in the browser and features dynamically updated HTML and CSS powered by JavaScript code.', 'HTML, CSS, Javascript', 'front-end'),
    ('Code Quiz', 'https://github.com/auzzie13/quizHomework', 'https://auzzie13.github.io/quizHomework', 'A timer-based quiz application that stores high scores client-side.', 'HTML, CSS, Javascript', 'front-end'),
    ('Day Planner', 'https://github.com/auzzie13/dayPlanner', 'https://auzzie13.github.io/dayPlanner', 'A simple calendar application that allows the user to save events for each hour of the day. This app will run in the browser and feature dynamically updated HTML and CSS powered by jQuery.', 'JQuery, Javascript', 'front-end'),
    ('Weather Dashboard', 'https://github.com/auzzie13/weatherDashboard', 'https://auzzie13.github.io/weatherDashboard/', 'A weather dashboard application with search functionality to find current weather conditions and the future weather outlook for multiple cities.', 'HTML, CSS, JQuery, Javascript', 'front-end'),
    ('Food and Fun', 'https://github.com/ppaytonjr/GamesnGamez', 'https://ppaytonjr.github.io/GamesnGamez/', 'A front-end entertainment application that allows user to search for concerts, sporting events, and restaurants based on a city of their choosing.  This allows the user to better plan a night of food and fun in an unfamiliar city.', 'HTML, CSS, JQuery, Javascript', 'front-end'),
    ('Developer Profile Generator', 'https://github.com/auzzie13/developerProfileGenerator', ' ', 'A command-line application that dynamically generates a PDF profile from a GitHub username.', 'Node, Javascript', 'node.js'),
    ('Note Taker', 'https://github.com/auzzie13/noteTaker', 'https://notetaker-austin.herokuapp.com/', 'An application that can be used to write, save, and delete notes. This application will use an express backend and save and retrieve note data from a JSON file.', 'Express, Javascript', 'back-end'),
    ('Eat-Da-Burger', 'https://github.com/auzzie13/burger', 'https://burger-austinw.herokuapp.com/', "Eat-Da-Burger! is a restaurant app that lets users input the names of burgers they'd like to eat. Whenever a user submits a burger's name, app will display the burger -- waiting to be devoured. Each burger in the waiting area also has a Devour it! button. Your app will store every burger in a database, whether devoured or not.", 'MySQL, Node, Express, Handlebars', 'back-end'),
    ('Node Master 2', 'https://github.com/jhumbrac/NodeMaster', 'https://nameless-journey-28810.herokuapp.com/', 'A text based adventure game with a Dungeons and Dragons type concept', 'Javascript, Sequelize', 'front-end'),
    ('Fitness Tracker', 'https://github.com/auzzie13/fitnessTracker', 'https://fitnesstracker-austinw.herokuapp.com/', 'A workout tracker that helps a consumer reach their fitness goals quicker when they track their workout progress.', 'Mongoose, Express, Javascript', 'back-end'),
    ('Budget Tracker', 'https://github.com/auzzie13/PWA-Budget-Tracker', 'https://budgettracker-aw.herokuapp.com/', 'Budget Tracker application that allows for offline access and functionality. The user will be able to add expenses and deposits to their budget with or without a connection. When entering transactions offline, they should populate the total when brought back online.', 'Mongoose, Express, Javascript', 'back-end'),
    ('Employee Directory', 'https://github.com/auzzie13/employeeDirectory', 'http://thawing-bayou-33619.herokuapp.com/', "An employee directory with React. Broke up application's UI into components, manage component state, and respond to user events.", 'React, Javascript', 'react'),
    ('Kibbles-N-Brews', 'https://github.com/Ztalley13/dogApp', 'https://kibbles-n-brews.herokuapp.com/', 'Kibbles-&-Brews is a user interactive app that allows people to not only find other people with size and breed compatible counterparts and playmates for their dogs, but it also allows them to blog about their beloved pets and allows user groups to find dog friendly places to gather.', 'Mongoose, Express, React, Node', 'mern'),
    ('React Portfolio', ' ', 'https://austin-d-williams.herokuapp.com', 'Another portfolio page built using M.E.R.N.', 'Mongoose, Express, React, Node', 'mern');

SELECT *
FROM projects;